### PR TITLE
Composer 5.x update

### PR DESCRIPTION
**Pull request by bbrink68**
Just changed the required laravel version from "~5.0" to "5.0.*" so I could install on my L5 install.  Thought I'd throw a PR just in case this was needed on the main repo.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This is totally wrong and makes no sense.

**Comment by bbrink68** [comment]
@GrahamCampbell This was not installing on Laravel 5.0.4 due to composer.json saying "~5.0" didn't satisfy my current Laravel 5 version.  Changing "~5.0" to "5.0.*" allows it to be installed on the latest Laravel 5 version,  what doesn't make sense?

**Comment by GrahamCampbell** [comment]
"~5.0" matches 5.0.4. This should be closed.

**Comment by bbrink68** [comment]
I thought the same, try to install on latest version of laravel though - it doesn't work without changing it:

    Problem 1
    - Conclusion: don't install laravel/framework v5.0.4
    - Conclusion: don't install laravel/framework v5.0.3
    - Conclusion: remove laravel/framework v5.0.2
    - Conclusion: don't install laravel/framework v5.0.2
    - Conclusion: don't install laravel/framework v5.0.1

**Comment by GrahamCampbell** [comment]
That can't be correct. Run `composer self-update` then `composer clear-cache`, then `rm -rf vendor` then `rm composer.lock`, then `composer install`.

**Comment by bbrink68** [comment]
Ran it, here is output: http://pastebin.com/TdXdM48k  Now all other composer.json refs to ~5.0 versions are saying the same thing.  Here is my composer.json http://pastebin.com/ve7cVT1Z

**Comment by GrahamCampbell** [comment]
This issue will be caused by another dependency asking for dev-master somewhere I imagine.

Never, ever use dev-master.

**Comment by bbrink68** [comment]
So In my composer.json, if I remove the single reference to a personal repo using dev-master - this should work?

**Comment by GrahamCampbell** [comment]
>  I remove the single reference to a personal repo using dev-master

You still don't need that. Use branch aliases.

**Comment by GrahamCampbell** [comment]
And no, I'm saying it's possible **another dependency** is doing something wrong.

**Comment by bbrink68** [comment]
Understood, sorry to have wasted your time. This can be closed.

**Comment by bbrink68** [comment]
I see a similar discussion here: https://laracasts.com/discuss/channels/general-discussion/unable-update-composerjson-file  perhaps a popular package causing this

**Comment by GrahamCampbell** [comment]
@bbrink68 You need to hit the close button. :)

**Pull request closed without merging**
